#!/usr/bin/env bash
# Compare Erg-generated bytecode against CPython-compiled reference bytecode.
#
# Usage:
#   ./tests/bytecode314/compare_bytecode.sh [python_command] [test_name]
#
# Examples:
#   ./tests/bytecode314/compare_bytecode.sh                     # all tests, auto-detect 3.14
#   ./tests/bytecode314/compare_bytecode.sh python3.14 for_loop # single test

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
REF_DIR="$SCRIPT_DIR/python_ref"

# Parse arguments
PY=""
FILTER=""
for arg in "$@"; do
    if [[ "$arg" == *python* || "$arg" == *bin/* ]]; then
        PY="$arg"
    else
        FILTER="$arg"
    fi
done

# Resolve Python command
if [[ -z "$PY" ]]; then
    UV_PY=$(find ~/.local/share/uv/python -maxdepth 1 -name 'cpython-3.14*' -print -quit 2>/dev/null || true)
    if [[ -n "$UV_PY" && -x "$UV_PY/bin/python3.14" ]]; then
        PY="$UV_PY/bin/python3.14"
    elif command -v python3.14 &>/dev/null; then
        PY="python3.14"
    else
        echo "ERROR: python3.14 not found." >&2
        exit 1
    fi
fi

echo "Python: $PY ($($PY --version 2>&1))"
echo ""

# Build
cargo build --manifest-path "$PROJECT_DIR/Cargo.toml" 2>&1 | tail -1
ERG="$PROJECT_DIR/target/debug/erg"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

for er_file in "$SCRIPT_DIR"/*.er; do
    name="$(basename "$er_file" .er)"
    py_file="$REF_DIR/${name}.py"

    # Filter
    [[ -n "$FILTER" && "$name" != "$FILTER" ]] && continue
    [[ ! -f "$py_file" ]] && continue

    echo "=== $name ==="

    # 1) Compile .er → .pyc with Erg
    erg_pyc="$TMPDIR/${name}_erg.pyc"
    if "$ERG" --py-command "$PY" --mode compile "$er_file" 2>/dev/null; then
        cp "${er_file%.er}.pyc" "$erg_pyc"
        rm -f "${er_file%.er}.pyc"
    else
        echo "  [Erg compile failed]"
        echo ""
        continue
    fi

    # 2) Compile .py → .pyc with CPython
    ref_pyc="$TMPDIR/${name}_ref.pyc"
    "$PY" -c "
import py_compile, sys
py_compile.compile('$py_file', '$ref_pyc', doraise=True)
" 2>/dev/null

    # 3) Disassemble both
    erg_dis="$TMPDIR/${name}_erg.dis"
    ref_dis="$TMPDIR/${name}_ref.dis"

    "$PY" -c "
import dis, marshal, sys

def disasm_pyc(path):
    with open(path, 'rb') as f:
        f.read(16)  # skip header (magic + flags + timestamp + size)
        code = marshal.load(f)
    dis.dis(code)

disasm_pyc('$erg_pyc')
" > "$erg_dis" 2>&1 || echo "  [Erg dis failed]"

    "$PY" -c "
import dis, marshal, sys

def disasm_pyc(path):
    with open(path, 'rb') as f:
        f.read(16)
        code = marshal.load(f)
    dis.dis(code)

disasm_pyc('$ref_pyc')
" > "$ref_dis" 2>&1 || echo "  [Ref dis failed]"

    # 4) Diff
    if diff -u "$ref_dis" "$erg_dis" --label="CPython ($name.py)" --label="Erg ($name.er)" > "$TMPDIR/diff.txt" 2>&1; then
        echo "  IDENTICAL"
    else
        echo "  DIFFERS:"
        # Show compact diff (skip identical lines)
        cat "$TMPDIR/diff.txt" | head -60
    fi
    echo ""
done
