//! Defines `Opcode313` (Python 3.13 bytecode opcodes).
//!
//! CPython 3.13 changes vs 3.12:
//! - **All opcodes renumbered** — numeric values completely different from 3.12
//! - HAVE_ARGUMENT = 44 (same threshold concept, different position)
//! - KW_NAMES removed → replaced by CALL_KW
//! - LOAD_CLOSURE is now a pseudo-opcode (258) → assembler maps to LOAD_FAST
//! - LOAD_METHOD is now a pseudo-opcode (259) → assembler maps to LOAD_ATTR
//! - New: TO_BOOL, CALL_KW, RETURN_CONST, FORMAT_SIMPLE, FORMAT_WITH_SPEC,
//!   LOAD_FAST_LOAD_FAST, STORE_FAST_LOAD_FAST, STORE_FAST_STORE_FAST, etc.
//! - New cache entries: POP_JUMP_IF_FALSE/TRUE (1), JUMP_BACKWARD (1)
//! - Magic number: 3571
//!
//! Source: CPython 3.13 Lib/opcode.py

#![allow(dead_code)]
#![allow(non_camel_case_types)]

use crate::impl_u8_enum;

impl_u8_enum! {Opcode313;
    CACHE = 0,
    BEFORE_ASYNC_WITH = 1,
    BEFORE_WITH = 2,
    // 3 is unused
    BINARY_SLICE = 4,
    BINARY_SUBSCR = 5,
    CHECK_EG_MATCH = 6,
    CHECK_EXC_MATCH = 7,
    CLEANUP_THROW = 8,
    DELETE_SUBSCR = 9,
    END_ASYNC_FOR = 10,
    END_FOR = 11,
    END_SEND = 12,
    EXIT_INIT_CHECK = 13,
    FORMAT_SIMPLE = 14,
    FORMAT_WITH_SPEC = 15,
    GET_AITER = 16,
    RESERVED = 17,
    GET_ANEXT = 18,
    GET_ITER = 19,
    GET_LEN = 20,
    GET_YIELD_FROM_ITER = 21,
    INTERPRETER_EXIT = 22,
    LOAD_ASSERTION_ERROR = 23,
    LOAD_BUILD_CLASS = 24,
    LOAD_LOCALS = 25,
    MAKE_FUNCTION = 26,
    MATCH_KEYS = 27,
    MATCH_MAPPING = 28,
    MATCH_SEQUENCE = 29,
    NOP = 30,
    POP_EXCEPT = 31,
    POP_TOP = 32,
    PUSH_EXC_INFO = 33,
    PUSH_NULL = 34,
    RETURN_GENERATOR = 35,
    RETURN_VALUE = 36,
    SETUP_ANNOTATIONS = 37,
    STORE_SLICE = 38,
    STORE_SUBSCR = 39,
    TO_BOOL = 40,
    UNARY_INVERT = 41,
    UNARY_NEGATIVE = 42,
    UNARY_NOT = 43,
    WITH_EXCEPT_START = 44,
    // --- opcodes >= 45 (HAVE_ARGUMENT) take an argument ---
    BINARY_OP = 45,
    BUILD_CONST_KEY_MAP = 46,
    BUILD_LIST = 47,
    BUILD_MAP = 48,
    BUILD_SET = 49,
    BUILD_SLICE = 50,
    BUILD_STRING = 51,
    BUILD_TUPLE = 52,
    CALL = 53,
    CALL_FUNCTION_EX = 54,
    CALL_INTRINSIC_1 = 55,
    CALL_INTRINSIC_2 = 56,
    CALL_KW = 57,
    COMPARE_OP = 58,
    CONTAINS_OP = 59,
    CONVERT_VALUE = 60,
    COPY = 61,
    COPY_FREE_VARS = 62,
    DELETE_ATTR = 63,
    DELETE_DEREF = 64,
    DELETE_FAST = 65,
    DELETE_GLOBAL = 66,
    DELETE_NAME = 67,
    DICT_MERGE = 68,
    DICT_UPDATE = 69,
    ENTER_EXECUTOR = 70,
    EXTENDED_ARG = 71,
    FOR_ITER = 72,
    GET_AWAITABLE = 73,
    IMPORT_FROM = 74,
    IMPORT_NAME = 75,
    IS_OP = 76,
    JUMP_BACKWARD = 77,
    JUMP_BACKWARD_NO_INTERRUPT = 78,
    JUMP_FORWARD = 79,
    LIST_APPEND = 80,
    LIST_EXTEND = 81,
    LOAD_ATTR = 82,
    LOAD_CONST = 83,
    LOAD_DEREF = 84,
    LOAD_FAST = 85,
    LOAD_FAST_AND_CLEAR = 86,
    LOAD_FAST_CHECK = 87,
    LOAD_FAST_LOAD_FAST = 88,
    LOAD_FROM_DICT_OR_DEREF = 89,
    LOAD_FROM_DICT_OR_GLOBALS = 90,
    LOAD_GLOBAL = 91,
    LOAD_NAME = 92,
    LOAD_SUPER_ATTR = 93,
    MAKE_CELL = 94,
    MAP_ADD = 95,
    MATCH_CLASS = 96,
    POP_JUMP_IF_FALSE = 97,
    POP_JUMP_IF_NONE = 98,
    POP_JUMP_IF_NOT_NONE = 99,
    POP_JUMP_IF_TRUE = 100,
    RAISE_VARARGS = 101,
    RERAISE = 102,
    RETURN_CONST = 103,
    SEND = 104,
    SET_ADD = 105,
    SET_FUNCTION_ATTRIBUTE = 106,
    SET_UPDATE = 107,
    STORE_ATTR = 108,
    STORE_DEREF = 109,
    STORE_FAST = 110,
    STORE_FAST_LOAD_FAST = 111,
    STORE_FAST_STORE_FAST = 112,
    STORE_GLOBAL = 113,
    STORE_NAME = 114,
    SWAP = 115,
    UNPACK_EX = 116,
    UNPACK_SEQUENCE = 117,
    YIELD_VALUE = 118,
    // 119–148: unused
    RESUME = 149,
    // 150–195: unused (reserved for future use)
    // --- Erg-specific opcodes (not used by CPython) ---
    // NOTE: 236–254 conflict with CPython's INSTRUMENTED_* opcodes,
    // but those only appear in tracing mode, not in .pyc files.
    ERG_POP_NTH = 196,
    ERG_PEEK_NTH = 197,
    ERG_INC = 198,
    ERG_DEC = 199,
    ERG_LOAD_FAST_IMMUT = 200,
    ERG_STORE_FAST_IMMUT = 201,
    ERG_MOVE_FAST = 202,
    ERG_CLONE_FAST = 203,
    ERG_COPY_FAST = 204,
    ERG_REF_FAST = 205,
    ERG_REF_MUT_FAST = 206,
    ERG_MOVE_OUTER = 207,
    ERG_CLONE_OUTER = 208,
    ERG_COPY_OUTER = 209,
    ERG_REF_OUTER = 210,
    ERG_REF_MUT_OUTER = 211,
    ERG_LESS_THAN = 212,
    ERG_LESS_EQUAL = 213,
    ERG_EQUAL = 214,
    ERG_NOT_EQUAL = 215,
    ERG_MAKE_SLOT = 216,
    ERG_MAKE_TYPE = 217,
    ERG_MAKE_PURE_FUNCTION = 218,
    ERG_CALL_PURE_FUNCTION = 219,
    // LOAD_CLOSURE is a pseudo-opcode (258) in 3.13; maps to LOAD_FAST in bytecode.
    // Use LOAD_FAST directly; opcode_set.rs handles the mapping.
    // LOAD_METHOD is a pseudo-opcode (259) in 3.13; maps to LOAD_ATTR in bytecode.
    // Use LOAD_ATTR directly; opcode_set.rs handles the mapping.
    ERG_LOAD_EMPTY_SLOT = 220,
    ERG_LOAD_EMPTY_STR = 221,
    ERG_LOAD_1_NAT = 222,
    ERG_LOAD_1_INT = 223,
    ERG_LOAD_1_REAL = 224,
    ERG_LOAD_NONE = 225,
    ERG_MUTATE = 226,
    ERG_STORE_SUBSCR = 227,
    ERG_BINARY_SUBSCR = 228,
    ERG_BINARY_RANGE = 229,
    ERG_TRY_BINARY_DIVIDE = 230,
    ERG_BINARY_TRUE_DIVIDE = 231,
    NOT_IMPLEMENTED = 255,
}

impl_u8_enum! {BinOpCode313;
    Add = 0, And = 1, FloorDiv = 2, LShift = 3, MatrixMultiply = 4,
    Multiply = 5, Remainder = 6, Or = 7, Power = 8, RShift = 9,
    Subtract = 10, TrueDivide = 11, Xor = 12,
    InplaceAdd = 13, InplaceAnd = 14, InplaceFloorDiv = 15, InplaceLShift = 16,
    InplaceMatrixMultiply = 17, InplaceMultiply = 18, InplaceRemainder = 19,
    InplaceOr = 20, InplacePower = 21, InplaceRShift = 22, InplaceSubtract = 23,
    InplaceTrueDivide = 24, InplaceXor = 25,
}
