name: Notify

on:
  push:
    branches: [main, notify-*]
    paths-ignore:
      - "doc/**"
      - ".github/**"
      - ".assets/**"
      - ".cargo/**"
      - "**.md"
      - "**.yml"
      - "LICENSE-**"
      - ".gitmessage"
      - ".pre-commit-config.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  notify-change:
    runs-on: ubuntu-latest
    steps:
      - name: notify to ergscripts
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mtshiba/ergscripts/dispatches \
            -d '{"event_type":"notification-push-main","client_payload":{"msg": "A change has been pushed", "branch": "${{ github.ref_name }}"}}'
      - name: notify to pytypes
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/erg-lang/pytypes/dispatches \
            -d '{"event_type":"notification-push-main","client_payload":{"msg": "A change has been pushed", "branch": "${{ github.ref_name }}"}}'
